### ISSUE TITLE
SDL OpenGL transparent background

### ISSUE THREAD

**Issue by petertribe** [kripken/emscripten#3406]
Hi,

Not sure if this is an issue or not, but using SDL and trying to have a transparent background so that the 3d model is rendered on the canvas but image under canvas shows thru. However doing...

        SDL_GL_SetAttribute( SDL_GL_RED_SIZE, 8 );
        SDL_GL_SetAttribute( SDL_GL_GREEN_SIZE, 8 );
        SDL_GL_SetAttribute( SDL_GL_BLUE_SIZE, 8 );
        SDL_GL_SetAttribute( SDL_GL_ALPHA_SIZE, 8 );
        SDL_GL_SetAttribute( SDL_GL_DEPTH_SIZE, 16 );
        SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, 1);
        SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, 4);
        SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);

        screen = SDL_SetVideoMode( _windowWidth, _windowHeight, 32, SDL_OPENGL );
        glClearColor(1,1,1,0.5);
        glClear(GL_COLOR_BUFFER_BIT);

i still get a fully opaque background....

**Comment by kripken** [comment]
On which browsers do you see it fail? Any GL warnings in the web console?

**Comment by petertribe** [comment]
No errors at all and tried mainly with chrome/safari, I tried looking a the existing samples but doesn't appear to be a sample that tries to do a transparent background.

**Comment by kripken** [comment]
Ok. I actually am not sure if that should work or not. @juj would know?

**Comment by juj** [comment]
It sounds like the alpha is prohibited by this line: https://github.com/kripken/emscripten/blob/incoming/src/library_browser.js#L278 . Does changing that to true enable alpha?

If so, we could add a build option to enable the transparency to the background canvas.

**Comment by eukarpov** [comment]
This problem has been actual for me too. Thanks @juj, it was useful reference to the code. I fixed it in this way.
```
src/library_sdl.js
388,389c388
<         stencil: (SDL.glAttributes[7 /*SDL_GL_STENCIL_SIZE*/] > 0),
<         alpha: (SDL.glAttributes[3 /*SDL_GL_ALPHA_SIZE*/] > 0)
---
>         stencil: (SDL.glAttributes[7 /*SDL_GL_STENCIL_SIZE*/] > 0)

src/library_browser.js
295,296c295
<         if (!contextAttributes["alpha"])
<           canvas.style.backgroundColor = "black";
---
>         canvas.style.backgroundColor = "black";
```

**Comment by juj** [comment]
I think this was fixed by the above commit and Emscripten no longer forcibly sets the CSS style to black, but instead that is configured by the shell, so to avoid the black background, you'll have to remove the CSS style in your custom shell config. I'll close this as resolved, assuming that was the root issue.

**Comment by mchiasson** [comment]
I can't figure out how to get a transparent background. I'm on Emscripten 1.37.21.  I modified the generated HTML from this:
```
canvas.emscripten { border: 0px none; background-color: black; }
```
into this
```
canvas.emscripten { border: 0px none; }
```
I'm using SDL2 from Emscripten ports. I've set the following attribute:
```C++
    SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
    SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);
    context = SDL_GL_CreateContext(window);
```
no luck. I still get a black background with `glClearColor(0, 0, 0, 0);` 

I also checked in `src/library_sdl.js` and it seems to already have the changes proposed by @eukarpov, and `src/library_browser.js` doesn't set the canvas style background color anymore

Any idea what I am missing?

**Comment by mchiasson** [comment]
I manually edited my `.js` output, located this line
```
if(webGLContextAttributes){for(var attribute in webGLContextAttributes){contextAttributes[attribute]=webGLContextAttributes[attribute]}}
```
and manually added this right after it
```
contextAttributes.alpha=true;
```
and that did the trick. my background is finally transparent. So something is going on with this `webGLContextAttributes` container. it looks like it has `alpha=false` in there.

**Comment by mchiasson** [comment]
Ok, I found a much better work around, which involves `<emscripten/html5.h>`

And then I replaced 
```C++
    SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_BUFFER_SIZE, 32);
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);

    // Create the OpenGL context required for OpenGL rendering.
    SDL_GLContext sdlGLContext;
    sdlGLContext = SDL_GL_CreateContext(g_pSDLWindow);
```
by this
```C++
    EmscriptenWebGLContextAttributes attr;
    emscripten_webgl_init_context_attributes(&attr);
    attr.alpha = 1;
    attr.depth = attr.stencil = attr.antialias = attr.preserveDrawingBuffer = attr.preferLowPowerToHighPerformance = attr.failIfMajorPerformanceCaveat = 0;
    attr.enableExtensionsByDefault = 1;
    attr.premultipliedAlpha = 0;
    attr.majorVersion = 1;
    attr.minorVersion = 0;
    EMSCRIPTEN_WEBGL_CONTEXT_HANDLE ctx = emscripten_webgl_create_context(0, &attr);
    emscripten_webgl_make_context_current(ctx);
```
where I explicity tell it to set `attr.alpha = 1;` since SDL2 doesn't seem to be capable of doing it.

**Comment by eukarpov** [comment]
Hey @mchiasson 

Yeah, you just need to setup alpha in SDL with this call
SDL_GL_SetAttribute( SDL_GL_ALPHA_SIZE, 5);

**Comment by mchiasson** [comment]
@eukarpov I did that, it doesn't work.

**Comment by mchiasson** [comment]
I just raised a new issue here: https://github.com/emscripten-ports/SDL2/issues/48, It's probably the right place for raising it.
