### ISSUE TITLE
Error when `python tests/runner.py` on Windows 10

### ISSUE THREAD

**Issue by SaschaNaz** [kripken/emscripten#4570]
Continues from #4549.

Error log:

```
C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin\llvm-link: c:/users/sasch/appdata/local/temptmp
yx3d2jstrlwr.c.o: error: Could not open input file: no such file or directory
C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin\llvm-link: error loading file 'c:/users/sasch/a
ppdata/local/temptmpyx3d2jstrlwr.c.o'
Traceback (most recent call last):
  File "C:\users\sasch\documents\github\emscripten\emcc", line 13, in <module>
    emcc.run()
  File "C:\users\sasch\documents\github\emscripten\emcc.py", line 1280, in run
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, in_temp, stdout, stderr, fo
rced=forced_stdlibs)
  File "C:\users\sasch\documents\github\emscripten\tools\system_libs.py", line 356, in calculate
    libfile = shared.Cache.get(name, do_create, extension=suffix)
  File "C:\users\sasch\documents\github\emscripten\tools\cache.py", line 41, in get
    temp = creator()
  File "C:\users\sasch\documents\github\emscripten\tools\system_libs.py", line 354, in do_create
    ret = create(name)
  File "C:\users\sasch\documents\github\emscripten\tools\system_libs.py", line 120, in create_libc
    return build_libc(libname, libc_files, args)
  File "C:\users\sasch\documents\github\emscripten\tools\system_libs.py", line 67, in build_libc
    shared.Building.link(o_s, in_temp(lib_filename))
  File "C:\users\sasch\documents\github\emscripten\tools\shared.py", line 1449, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output
AssertionError: Linking error:
[browser launch: page.html ]
ERROR
```

**Comment by SaschaNaz** [comment]
>Hmm, can you paste the contents of C:\users\sasch\.emscripten? Perhaps that would give a clue.

@juj This is the contents:

```
import os
LLVM_ROOT='C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin'
NODE_JS='C:/Program Files/Emscripten/node/4.1.1_64bit/bin/node'
PYTHON='C:/Program Files/Emscripten/python/2.7.5.3_64bit/python.exe'
JAVA='C:/Program Files/Emscripten/java/7.45_64bit/bin/java.exe'
EMSCRIPTEN_ROOT='C:/Program Files/Emscripten/emscripten/incoming'
EMSCRIPTEN_NATIVE_OPTIMIZER='C:/Program Files/Emscripten/emscripten/incoming_64bit_optimizer/RelWithDebInfo/optimizer.exe'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = 'c:/users/sasch/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```

**Comment by juj** [comment]
One issue here is that `EMSCRIPTEN_ROOT` is pointing to program files, but you are running with Emscripten from `C:\users\sasch\documents\github\emscripten`. This will at minimum need `EMSCRIPTEN_ROOT` pointed to the new location, although I'm not quite sure if some other things might need configuring as well, that scheme is not much tested.

The verified way to use emsdk with your own github branch is mentioned in here: https://github.com/juj/emsdk#how-do-i-use-my-own-emscripten-github-fork-with-the-sdk . That avoids having to change the `.emscripten` config file "after the fact".

The above issue still eerily reminds me of something that would have been fixed before, so perhaps `C:\users\sasch\documents\github\emscripten` is not up to latest in the `incoming` branch? Does the unmodified test pass in unmodified `incoming` branch obtained directly `emsdk install --vs2015 sdk-incoming-64bit` + `emsdk activate --vs2015 sdk-incoming-64bit`?

**Comment by SaschaNaz** [comment]
My branch was just 12 days old but pulling from latest incoming branch fixed the link problem. The tests randomly die when using Edge, however...

```
PS C:\Users\sasch\documents\github\emscripten> python tests/runner.py browser.test_worker_api_sleep
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_browser']
Running test_browser: (1 tests)
[Browser harness server on process 14860]

Running the browser tests. Make sure the browser allows popups from localhost.

test_worker_api_sleep (test_browser.browser) ... [browser launch: test.html ]
ERROR
[Browser harness server terminated]

======================================================================
ERROR: test_worker_api_sleep (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sasch\documents\github\emscripten\tests\test_browser.py", line 2007, in test_worker_api_sleep
    self.btest('worker_api_main.cpp', expected='566')
  File "C:\Users\sasch\documents\github\emscripten\tests\runner.py", line 910, in btest
    self.run_browser(outfile + url_suffix, message, ['/report_result?' + e for e in expected], timeout=timeout)
  File "C:\Users\sasch\documents\github\emscripten\tests\runner.py", line 770, in run_browser
    self.assertIdentical(expectedResult, output)
  File "C:\Users\sasch\documents\github\emscripten\tests\runner.py", line 477, in assertIdentical
    limit_size(''.join([a.rstrip()+'\n' for a in difflib.unified_diff(x.split('\n'), y.split('\n'), fromfile='expected',
 tofile='actual')]))
Exception: Expected to have '/report_result?566' == '[no http server activity]', diff:

--- expected
+++ actual
@@ -1 +1 @@
-/report_result?566
+[no http server activity]


----------------------------------------------------------------------
Ran 1 test in 26.374s

FAILED (errors=1)
PS C:\Users\sasch\documents\github\emscripten>
```

**Comment by juj** [comment]
Yeah, Edge might not be a good test harness browser. Try setting `set EMSCRIPTEN_BROWSER=C:/program files(x86)/Mozilla Firefox/firefox.exe` or similar, that should have better success.

**Comment by SaschaNaz** [comment]
Still getting 50 errors on Firefox but anyway no linking errors. Thanks!
